name = "CantStop"
uuid = "078a070c-0203-4da7-b1d6-6b458fb9d52e"
authors = ["itsdfish <itsdfish@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
